[project]
version = "0.0.1"
name = "lib-not-dr"
description = "A python lib created from Difficult Rocket development"
readme = "README.md"
authors = [
    {name = "shenjackyuanjie", email = "3695888@qq.com"}
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
[project.license]
file = "LICENSE"
text = "MPL-2.0"
